### ISSUE TITLE
Decide on Design Inspiration for Portfolio

### ISSUE THREAD

**Issue by tteltrab** [ZacharyJBartlett/Bootstrap-Portfolio#1]
Find another portfolio website to model yours off of. Ideally a web developer's portfolio website.

Link to 3 of your favorites as a comment in this issue.

**Comment by tteltrab** [comment]
Should be professional. I wouldn't do anything too crazy. Just something to cleanly and professionally describe your experience, your interests, and yourself.

I'd take a look at these websites for inspiration:

https://www.awwwards.com/websites/portfolio/
or blogs like
https://www.shopify.com/partners/blog/web-design-portfolio-inspiration

You know, just google things like "portfolio websites".

I'd start out by finding 5 or 6 you like, and then narrowing it down to 3.

**Comment by ZacharyJBartlett** [comment]
portfolio #1

http://y78.fr/
portfolio #2

http://www.rleonardi.com/interactive-resume/
portfolio #3

http://mrcthms.com/

**Comment by tteltrab** [comment]
Something like this is obviously possible: http://y78.fr/2/ . 

I'd say you can use this as your baseline. It's not mobile responsive, but you could fix that with this design. It would probably need some changes.

http://www.rleonardi.com/interactive-resume/ is cool, but not really a reasonable MVP for your first portfolio website. lol.

http://mrcthms.com/ is good aesthetically, but provides no real obvious way to showcase any of your work or talk about your experience. It also doesn't demonstrate your ability in any way.

**Comment by tteltrab** [comment]
If you really like Marc's, use that as a baseline. Find 3 designs that look like that one, but expand the content. 

You want to both showcase your material and demonstrate your ability. You'll need a place to talk about you, to show some screenshots of work you've done, and to link out to things like github, your deployed sites, etc.

You also want the portfolio page itself to look interesting/have some interesting aspect that hooks people. Could be that it's very clean or interesting looking, it interacts in some interesting way when you scroll, etc.

**Comment by tteltrab** [comment]
If you have an idea that uses a simpler/different design that you think you could modify to fit your use case, feel free to share a mock up.

**Comment by tteltrab** [comment]
Could use a tool like https://moqups.com/ , https://balsamiq.com/ , or a similar alternative.

**Comment by ZacharyJBartlett** [comment]
closed by #3
